### ISSUE TITLE
Clarify CC attribution requirements

### ISSUE THREAD

**Issue by adambiggs** [fguillen/MDMagick#1]
Nice work on MDMagick!

I'd like to fork this project and potentially send you some pull requests, but could you clarify the attribution requirements a little more.

If all that's required is a note in the comments, that would be totally fine. But if your license requires attribution that's visible to our users... I'll have to look for a different tool or write my own :(

**Comment by fguillen** [comment]
Changed to MIT License, I hope this reduces the requirements as much as you need. 

Sorry to answer so late, I didn't realize I had "notifications" pending :)

**Comment by adambiggs** [comment]
Great, thanks!
